module SrcLoc where

import Data.Text (Text)

data RealSrcLoc
  = SrcLoc !Text !Int !Int
  deriving (Show)

data SrcLoc
  = RealSrcLoc !RealSrcLoc
  | UnhelpfulLoc !Text -- code generated by the compiler
  deriving (Show)

data RealSrcSpan = SrcSpan
  { srcSpanFile :: !Text,
    startLine :: !Int,
    startCol :: !Int,
    endLine :: !Int,
    endCol :: !Int
  }
  deriving (Show)

data SrcSpan
  = RealSrcSpan !RealSrcSpan
  | UnhelpfulSpan !Text
  deriving (Show)
